[project]
name = "doctr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-doctr[torch]",
    "ultralytics",
    "opencv-python>=4.8",
    "numpy",
    "ipykernel"
]
